/* ============================================================
   MOZZAFIATO — Índice completo del menú
   Usado por el buscador del index.html
   type: 'simple' | 'picker'
   picker: 'pasta' | 'latte' | 'tisana' | 'waffle'
   cartName: nombre exacto que va al carrito (para simples)
   page: archivo HTML donde está
   ============================================================ */

const MENU_DATA = [

  /* ── DESAYUNOS ── */
  { name: 'Desayuno completo',            cat: 'Paquetes',         page: 'page1.html', cartName: 'Paquete · Desayuno completo' },
  { name: 'Desayuno americano',           cat: 'Paquetes',         page: 'page1.html', cartName: 'Paquete · Desayuno americano' },
  { name: 'Combo continental',            cat: 'Paquetes',         page: 'page1.html', cartName: 'Paquete · Combo continental' },
  { name: 'Combo niños',                  cat: 'Paquetes',         page: 'page1.html', cartName: 'Paquete · Combo niños' },
  { name: 'Huevos al gusto',              cat: 'Huevos',           page: 'page1.html', cartName: 'Huevos · Huevos al gusto' },
  { name: 'Huevos con machaca de res',    cat: 'Huevos',           page: 'page1.html', cartName: 'Huevos · Huevos con machaca de res' },
  { name: 'Huevos divorciados',           cat: 'Huevos',           page: 'page1.html', cartName: 'Huevos · Huevos divorciados' },
  { name: 'Huevos rancheros',             cat: 'Huevos',           page: 'page1.html', cartName: 'Huevos · Huevos rancheros' },
  { name: 'Huevos motuleños',             cat: 'Huevos',           page: 'page1.html', cartName: 'Huevos · Huevos motuleños' },
  { name: 'Omelette Champiñones',         cat: 'Omelettes',        page: 'page1.html', cartName: 'Omelette · Champiñones' },
  { name: 'Omelette Vegetariano',         cat: 'Omelettes',        page: 'page1.html', cartName: 'Omelette · Vegetariano' },
  { name: 'Omelette Clásico',             cat: 'Omelettes',        page: 'page1.html', cartName: 'Omelette · Clásico' },
  { name: 'Omelette con chilaquiles rojos', cat: 'Omelettes',      page: 'page1.html', cartName: 'Omelette · Omelette con chilaquiles rojos' },
  { name: 'Chilaquiles con huevo',        cat: 'Chilaquiles',      page: 'page1.html', cartName: 'Chilaquiles · Con huevo' },
  { name: 'Chilaquiles con pollo',        cat: 'Chilaquiles',      page: 'page1.html', cartName: 'Chilaquiles · Con pollo' },
  { name: 'Chilaquiles con arrachera',    cat: 'Chilaquiles',      page: 'page1.html', cartName: 'Chilaquiles · Arrachera' },
  { name: 'Cóctel de frutas',             cat: 'Desayunos',        page: 'page1.html', cartName: 'Cóctel de frutas' },

  /* ── ENSALADAS & PLATILLOS ── */
  { name: 'Ensalada Mozzafiato VIP',      cat: 'Ensaladas',        page: 'page2.html', cartName: 'Ensalada Mozzafiato VIP' },
  { name: 'Ensalada Arrachera Grill',     cat: 'Ensaladas',        page: 'page2.html', cartName: 'Arrachera Grill' },
  { name: 'Ensalada de pollo',            cat: 'Ensaladas',        page: 'page2.html', cartName: 'Ensalada de pollo' },
  { name: 'Ensalada de fresas y arándanos', cat: 'Ensaladas',      page: 'page2.html', cartName: 'Ensalada de fresas y arándanos' },
  { name: 'Ensalada cesar',               cat: 'Ensaladas',        page: 'page2.html', cartName: 'Ensalada cesar' },
  { name: 'Ensalada mexicana',            cat: 'Ensaladas',        page: 'page2.html', cartName: 'Ensalada mexicana' },
  { name: 'Ensalada caribeña',            cat: 'Ensaladas',        page: 'page2.html', cartName: 'Ensalada caribeña' },
  { name: 'Ensalada de mango con manzana verde', cat: 'Ensaladas', page: 'page2.html', cartName: 'Ensalada de mango con manzana verde' },
  { name: 'Ensalada de jamón serrano y pera', cat: 'Ensaladas',    page: 'page2.html', cartName: 'Ensalada de jamón serrano y pera' },
  { name: 'Pechuga de pollo a la plancha', cat: 'Platillos',       page: 'page2.html', cartName: 'Pechuga de pollo a la plancha' },
  { name: 'Arrachera Grill',              cat: 'Platillos',        page: 'page2.html', cartName: 'Arrachera Grill' },

  /* ── CHAPATAS & HAMBURGUESAS ── */
  { name: 'Chapata Mar y Tierra',         cat: 'Chapatas',         page: 'page3.html', cartName: 'Chapata · Mar y Tierra' },
  { name: 'Chapata Clásica especial',     cat: 'Chapatas',         page: 'page3.html', cartName: 'Chapata · Clásica especial' },
  { name: 'Chapata Pepito',               cat: 'Chapatas',         page: 'page3.html', cartName: 'Chapata · Pepito' },
  { name: 'Chapata Arachera grill',       cat: 'Chapatas',         page: 'page3.html', cartName: 'Chapata · Arachera grill' },
  { name: 'Chapata Jamón Serrano',        cat: 'Chapatas',         page: 'page3.html', cartName: 'Chapata · Jamón Serrano' },
  { name: 'Chapata Pechuga de pollo',     cat: 'Chapatas',         page: 'page3.html', cartName: 'Chapata · Pechuga de pollo' },
  { name: 'Chapata Preciosa',             cat: 'Chapatas',         page: 'page3.html', cartName: 'Chapata · Preciosa' },
  { name: 'Chapata Mexicana',             cat: 'Chapatas',         page: 'page3.html', cartName: 'Chapata · Mexicana' },
  { name: 'Mollete',                      cat: 'Molletes',         page: 'page3.html', cartName: 'Mollete' },
  { name: 'Croissant Tocino',             cat: 'Croissants',       page: 'page3.html', cartName: 'Croissant · Tocino' },
  { name: 'Croissant Jamón Serrano',      cat: 'Croissants',       page: 'page3.html', cartName: 'Croissant · Jamón Serrano' },
  { name: 'Croissant Pechuga de pollo',   cat: 'Croissants',       page: 'page3.html', cartName: 'Croissant · Pechuga de pollo' },
  { name: 'Croissant Arrachera grill',    cat: 'Croissants',       page: 'page3.html', cartName: 'Croissant · Arrachera grill' },
  { name: 'Croissant Clásico',            cat: 'Croissants',       page: 'page3.html', cartName: 'Croissant · Clásico' },
  { name: 'Croissant Madame',             cat: 'Croissants',       page: 'page3.html', cartName: 'Croissant · Madame' },
  { name: 'Croissant Mozzafiato',         cat: 'Croissants',       page: 'page3.html', cartName: 'Croissant · Mozzafiato' },
  { name: 'Hamburguesa Clásica',          cat: 'Hamburguesas',     page: 'page3.html', cartName: 'Hamburguesa · Clásica' },
  { name: 'Hamburguesa Paraíso',          cat: 'Hamburguesas',     page: 'page3.html', cartName: 'Hamburguesa · Paraíso' },
  { name: 'Hamburguesa Mar y tierra',     cat: 'Hamburguesas',     page: 'page3.html', cartName: 'Hamburguesa · Mar y tierra' },
  { name: 'Guacamole Burger',             cat: 'Hamburguesas',     page: 'page3.html', cartName: 'Hamburguesa · Guacamole Burger' },

  /* ── SANDWICHES, WAFFLES & CREPAS ── */
  { name: 'Sandwich BLT',                 cat: 'Sandwiches',       page: 'page4.html', cartName: 'Sandwich · BLT' },
  { name: 'Sandwich Mediterraneo',        cat: 'Sandwiches',       page: 'page4.html', cartName: 'Sandwich · Mediterraneo' },
  { name: 'Sandwich Vegetariano',         cat: 'Sandwiches',       page: 'page4.html', cartName: 'Sandwich · Vegetariano' },
  { name: 'Club Sandwich',                cat: 'Club Sandwiches',  page: 'page4.html', cartName: 'Club Sandwich · Club Sandwich' },
  { name: 'Club Sandwich BLT',            cat: 'Club Sandwiches',  page: 'page4.html', cartName: 'Club Sandwich · Club Sandwich BLT' },
  { name: 'Waffle salado Clásico',        cat: 'Waffles Salados',  page: 'page4.html', cartName: 'Waffle Salado · Waffle clásico' },
  { name: 'Waffle de la granja',          cat: 'Waffles Salados',  page: 'page4.html', cartName: 'Waffle Salado · Waffle de la granja' },
  { name: 'Club Waffle',                  cat: 'Waffles Salados',  page: 'page4.html', cartName: 'Waffle Salado · Club Waffle' },
  { name: 'Crepa clásica',                cat: 'Crepas Saladas',   page: 'page4.html', cartName: 'Crepa Salada · Crepa clásica' },
  { name: 'Crepa de Jamón Serrano',       cat: 'Crepas Saladas',   page: 'page4.html', cartName: 'Crepa Salada · Crepa de Jamón Serrano' },
  { name: 'Crepa de champiñones',         cat: 'Crepas Saladas',   page: 'page4.html', cartName: 'Crepa Salada · Crepa de champiñones' },

  /* ── PASTAS ── */
  { name: 'Pasta',                        cat: 'Pastas',           page: 'page5.html', type: 'picker', picker: 'pasta' },
  { name: 'Lasagna',                      cat: 'Pastas',           page: 'page5.html', cartName: 'Lasagna' },

  /* ── WAFFLES DULCES & POSTRES ── */
  { name: 'Waffle / Hotcake Clásicos y ligeros', cat: 'Waffles Dulces', page: 'page6.html', type: 'picker', picker: 'waffle', pickerName: 'Clásicos y ligeros' },
  { name: 'Waffle / Hotcake Compota de frutos rojos', cat: 'Waffles Dulces', page: 'page6.html', type: 'picker', picker: 'waffle', pickerName: 'Compota de frutos rojos' },
  { name: 'Waffle / Hotcake Oreo',        cat: 'Waffles Dulces',   page: 'page6.html', type: 'picker', picker: 'waffle', pickerName: 'Oreo' },
  { name: 'Waffle / Hotcake Compota de manzana', cat: 'Waffles Dulces', page: 'page6.html', type: 'picker', picker: 'waffle', pickerName: 'Compota de manzana' },
  { name: 'Crepa Dulce Cajeta y nuez',    cat: 'Crepas Dulces',    page: 'page6.html', cartName: 'Crepa Dulce · Cajeta y nuez' },
  { name: 'Crepa Dulce Fresa y crema de avellana', cat: 'Crepas Dulces', page: 'page6.html', cartName: 'Crepa Dulce · Fresa y crema de avellana' },
  { name: 'Crepa Dulce Queso de bola',    cat: 'Crepas Dulces',    page: 'page6.html', cartName: 'Crepa Dulce · Queso de bola' },
  { name: 'Crepa Dulce Compota de frutos rojos', cat: 'Crepas Dulces', page: 'page6.html', cartName: 'Crepa Dulce · Compota de frutos rojos' },
  { name: 'Crepa Dulce Compota de manzana', cat: 'Crepas Dulces',  page: 'page6.html', cartName: 'Crepa Dulce · Compota de manzana' },
  { name: 'Pan de zanahoria',             cat: 'Postres',          page: 'page6.html', cartName: 'Postre · Pan de zanahoria' },
  { name: 'Pan de elote',                 cat: 'Postres',          page: 'page6.html', cartName: 'Postre · Pan de elote' },
  { name: 'Affogato',                     cat: 'Postres',          page: 'page6.html', cartName: 'Postre · Affogato' },
  { name: 'Cheesecake japonés',           cat: 'Postres',          page: 'page6.html', cartName: 'Postre · Cheesecake japonés' },
  { name: 'Pay de limón eureka',          cat: 'Postres',          page: 'page6.html', cartName: 'Postre · Pay de limón eureka' },
  { name: 'Tostado francés',              cat: 'Postres',          page: 'page6.html', cartName: 'Postre · Tostado francés' },

  /* ── BEBIDAS CALIENTES ── */
  { name: 'Espresso',                     cat: 'Café Clásico',     page: 'page7.html', cartName: 'Café · Espresso' },
  { name: 'Espresso doble',               cat: 'Café Clásico',     page: 'page7.html', cartName: 'Café · Espresso doble' },
  { name: 'Espresso doble macchiato',     cat: 'Café Clásico',     page: 'page7.html', cartName: 'Café · Espresso doble macchiato' },
  { name: 'Espresso doble cortado',       cat: 'Café Clásico',     page: 'page7.html', cartName: 'Café · Espresso doble cortado' },
  { name: 'Americano de espresso',        cat: 'Café Clásico',     page: 'page7.html', cartName: 'Café · Americano de espresso' },
  { name: 'Americano de espresso doble',  cat: 'Café Clásico',     page: 'page7.html', cartName: 'Café · Americano de espresso doble' },
  { name: 'Lechero 1 shot',               cat: 'Café Clásico',     page: 'page7.html', cartName: 'Café · Lechero (1 shot)' },
  { name: 'Lechero intenso 2 shots',      cat: 'Café Clásico',     page: 'page7.html', cartName: 'Café · Lechero intenso (2 shots)' },
  { name: 'Chocolate Blanco',             cat: 'Chocolates',       page: 'page7.html', cartName: 'Chocolate · Blanco' },
  { name: 'Chocolate Oaxaca',             cat: 'Chocolates',       page: 'page7.html', cartName: 'Chocolate · Oaxaca' },
  { name: 'Chocolate Europeo',            cat: 'Chocolates',       page: 'page7.html', cartName: 'Chocolate · Europeo' },
  { name: 'Chocolate Chocomenta',         cat: 'Chocolates',       page: 'page7.html', cartName: 'Chocolate · Chocomenta' },
  { name: 'Chocolate con Cacahuate',      cat: 'Chocolates',       page: 'page7.html', cartName: 'Chocolate · Chocolate c/ Cacahuate' },
  { name: 'Latte Clásico',               cat: 'Lattes & Cappuccinos', page: 'page7.html', type: 'picker', picker: 'latte', pickerName: 'Clásico' },
  { name: 'Latte Moka',                   cat: 'Lattes & Cappuccinos', page: 'page7.html', type: 'picker', picker: 'latte', pickerName: 'Moka' },
  { name: 'Latte Cajeta',                 cat: 'Lattes & Cappuccinos', page: 'page7.html', type: 'picker', picker: 'latte', pickerName: 'Cajeta' },
  { name: 'Latte Caramelo',               cat: 'Lattes & Cappuccinos', page: 'page7.html', type: 'picker', picker: 'latte', pickerName: 'Caramelo' },
  { name: 'Latte Cacahuate',              cat: 'Lattes & Cappuccinos', page: 'page7.html', type: 'picker', picker: 'latte', pickerName: 'Cacahuate' },
  { name: 'Latte Crema de avellana',      cat: 'Lattes & Cappuccinos', page: 'page7.html', type: 'picker', picker: 'latte', pickerName: 'Crema de avellana' },
  { name: 'Latte Vainilla',               cat: 'Lattes & Cappuccinos', page: 'page7.html', type: 'picker', picker: 'latte', pickerName: 'Vainilla' },
  { name: 'Latte Licor de café',          cat: 'Lattes & Cappuccinos', page: 'page7.html', type: 'picker', picker: 'latte', pickerName: 'Licor de café' },
  { name: 'Latte Crema irlandesa',        cat: 'Lattes & Cappuccinos', page: 'page7.html', type: 'picker', picker: 'latte', pickerName: 'Crema irlandesa' },
  { name: 'Latte Malvavisco tostado',     cat: 'Lattes & Cappuccinos', page: 'page7.html', type: 'picker', picker: 'latte', pickerName: 'Malvavisco tostado' },
  { name: 'Latte Nuez de Macadamia',      cat: 'Lattes & Cappuccinos', page: 'page7.html', type: 'picker', picker: 'latte', pickerName: 'Nuez de Macadamia' },
  { name: 'Latte Té chai',                cat: 'Lattes & Cappuccinos', page: 'page7.html', type: 'picker', picker: 'latte', pickerName: 'Té chai' },
  { name: 'Latte Té matcha',              cat: 'Lattes & Cappuccinos', page: 'page7.html', type: 'picker', picker: 'latte', pickerName: 'Té matcha' },
  { name: 'Té Exótico Yin Yang Tónic',   cat: 'Tés Exóticos',     page: 'page7.html', cartName: 'Té Exótico · Yin Yang Tónic' },
  { name: 'Té Exótico Fusion Herbal',     cat: 'Tés Exóticos',     page: 'page7.html', cartName: 'Té Exótico · Fusion Herbal' },
  { name: 'Té Exótico Detóx',             cat: 'Tés Exóticos',     page: 'page7.html', cartName: 'Té Exótico · Detóx' },
  { name: 'Té Exótico Oriental',          cat: 'Tés Exóticos',     page: 'page7.html', cartName: 'Té Exótico · Oriental' },
  { name: 'Té Exótico Floral',            cat: 'Tés Exóticos',     page: 'page7.html', cartName: 'Té Exótico · Floral' },

  /* ── TISANAS & BEBIDAS FRÍAS ── */
  { name: 'Tisana Manzana almendras',     cat: 'Tisanas',          page: 'page8.html', type: 'picker', picker: 'tisana', pickerName: 'Manzana almendras' },
  { name: 'Tisana Pétalos de rosas',      cat: 'Tisanas',          page: 'page8.html', type: 'picker', picker: 'tisana', pickerName: 'Pétalos de rosas' },
  { name: 'Tisana Ponche de guayaba',     cat: 'Tisanas',          page: 'page8.html', type: 'picker', picker: 'tisana', pickerName: 'Ponche de guayaba' },
  { name: 'Tisana Moras del bosque',      cat: 'Tisanas',          page: 'page8.html', type: 'picker', picker: 'tisana', pickerName: 'Moras del bosque' },
  { name: 'Tisana Fresa Kiwi',            cat: 'Tisanas',          page: 'page8.html', type: 'picker', picker: 'tisana', pickerName: 'Fresa Kiwi' },
  { name: 'Té Frío Yin Yang Tónic',       cat: 'Tés Fríos',        page: 'page8.html', cartName: 'Té Frío · Yin Yang Tónic' },
  { name: 'Té Frío Fusion Herbal',        cat: 'Tés Fríos',        page: 'page8.html', cartName: 'Té Frío · Fusion Herbal' },
  { name: 'Té Frío Arizona',              cat: 'Tés Fríos',        page: 'page8.html', cartName: 'Té Frío · Arizona' },
  { name: 'Agua Fresca Fresada',          cat: 'Bebidas Frías',    page: 'page8.html', cartName: 'Agua Fresca · Fresada' },
  { name: 'Agua Fresca Zarzamora',        cat: 'Bebidas Frías',    page: 'page8.html', cartName: 'Agua Fresca · Zarzamora' },
  { name: 'Agua Fresca Frutos Rojos',     cat: 'Bebidas Frías',    page: 'page8.html', cartName: 'Agua Fresca · Frutos Rojos' },
  { name: 'Limonada natural',             cat: 'Bebidas Frías',    page: 'page8.html', cartName: 'Limonada natural' },
  { name: 'Limonada mineral',             cat: 'Bebidas Frías',    page: 'page8.html', cartName: 'Limonada mineral' },
  { name: 'Jugo de naranja',              cat: 'Bebidas Frías',    page: 'page8.html', cartName: 'Jugo de naranja' },
  { name: 'Horchata de crema de coco',    cat: 'Bebidas Frías',    page: 'page8.html', cartName: 'Horchata de crema de coco' },

  /* ── FRAPPES & SMOOTHIES ── */
  { name: 'Frappe Capuccino',             cat: 'Frappes',          page: 'page9.html', cartName: 'Frappe · Capuccino' },
  { name: 'Frappe Chocomenta',            cat: 'Frappes',          page: 'page9.html', cartName: 'Frappe · Chocomenta' },
  { name: 'Frappe Chocomenta con cacahuate', cat: 'Frappes',       page: 'page9.html', cartName: 'Frappe · Chocomenta con cacahuate' },
  { name: 'Frappe Moka',                  cat: 'Frappes',          page: 'page9.html', cartName: 'Frappe · Moka' },
  { name: 'Frappe Cacahuate',             cat: 'Frappes',          page: 'page9.html', cartName: 'Frappe · Cacahuate' },
  { name: 'Frappe Cajeta',                cat: 'Frappes',          page: 'page9.html', cartName: 'Frappe · Cajeta' },
  { name: 'Frappe Crema de avellana',     cat: 'Frappes',          page: 'page9.html', cartName: 'Frappe · Crema de avellana' },
  { name: 'Frappe Vainilla',              cat: 'Frappes',          page: 'page9.html', cartName: 'Frappe · Vainilla' },
  { name: 'Frappe Caramelo',              cat: 'Frappes',          page: 'page9.html', cartName: 'Frappe · Caramelo' },
  { name: 'Frappe Queso de bola',         cat: 'Frappes',          page: 'page9.html', cartName: 'Frappe · Queso de bola' },
  { name: 'Frappe Licor de café',         cat: 'Frappes',          page: 'page9.html', cartName: 'Frappe · Licor de café' },
  { name: 'Frappe Crema irlandesa',       cat: 'Frappes',          page: 'page9.html', cartName: 'Frappe · Crema irlandesa' },
  { name: 'Frappe Malvavisco tostado',    cat: 'Frappes',          page: 'page9.html', cartName: 'Frappe · Malvavisco tostado' },
  { name: 'Frappe Oreo',                  cat: 'Frappes',          page: 'page9.html', cartName: 'Frappe · Oreo' },
  { name: 'Smoothie Taro',                cat: 'Smoothies',        page: 'page9.html', cartName: 'Smoothie · Taro' },
  { name: 'Smoothie Fresa cremosa',       cat: 'Smoothies',        page: 'page9.html', cartName: 'Smoothie · Fresa cremosa' },
  { name: 'Smoothie Chicle',              cat: 'Smoothies',        page: 'page9.html', cartName: 'Smoothie · Chicle' },
  { name: 'Smoothie Té chai',             cat: 'Smoothies',        page: 'page9.html', cartName: 'Smoothie · Té chai' },
  { name: 'Smoothie Chocolate Blanco',    cat: 'Smoothies',        page: 'page9.html', cartName: 'Smoothie · Chocolate Blanco' },
  { name: 'Smoothie Chocolate Oaxaca',    cat: 'Smoothies',        page: 'page9.html', cartName: 'Smoothie · Chocolate Oaxaca' },
  { name: 'Smoothie Chocolate Europeo',   cat: 'Smoothies',        page: 'page9.html', cartName: 'Smoothie · Chocolate Europeo' },
  { name: 'Smoothie Té Matcha',           cat: 'Smoothies',        page: 'page9.html', cartName: 'Smoothie · Té Matcha' },
  { name: 'Smoothie Mango',               cat: 'Smoothies',        page: 'page9.html', cartName: 'Smoothie · Mango' },
  { name: 'Smoothie Fresa',               cat: 'Smoothies',        page: 'page9.html', cartName: 'Smoothie · Fresa' },
  { name: 'Smoothie Limón',               cat: 'Smoothies',        page: 'page9.html', cartName: 'Smoothie · Limón' },
  { name: 'Smoothie Naranja',             cat: 'Smoothies',        page: 'page9.html', cartName: 'Smoothie · Naranja' },
  { name: 'Smoothie Daiquirí Fresón',     cat: 'Smoothies',        page: 'page9.html', cartName: 'Smoothie · Daiquirí Fresón' },
  { name: 'Smoothie Maracuya',            cat: 'Smoothies',        page: 'page9.html', cartName: 'Smoothie · Maracuya' },
  { name: 'Smoothie Tamarindo',           cat: 'Smoothies',        page: 'page9.html', cartName: 'Smoothie · Tamarindo' },
  { name: 'Smoothie Piña con Coco',       cat: 'Smoothies',        page: 'page9.html', cartName: 'Smoothie · Piña con Coco' },
  { name: 'Smoothie Zarzamora',           cat: 'Smoothies',        page: 'page9.html', cartName: 'Smoothie · Zarzamora' },
  { name: 'Smoothie Mix frutos rojos',    cat: 'Smoothies',        page: 'page9.html', cartName: 'Smoothie · Mix frutos rojos' },
  { name: 'Smoothie Baileys Crema de avellana', cat: 'Smoothies Baileys', page: 'page9.html', cartName: 'Smoothie · Crema de avellana' },
  { name: 'Smoothie Baileys Cajeta',      cat: 'Smoothies Baileys', page: 'page9.html', cartName: 'Smoothie · Cajeta' },
  { name: 'Smoothie Yogurt Fresa',        cat: 'Smoothies Yogurt', page: 'page9.html', cartName: 'Smoothie · Fresa' },
  { name: 'Smoothie Yogurt Mango',        cat: 'Smoothies Yogurt', page: 'page9.html', cartName: 'Smoothie · Mango' },
  { name: 'Smoothie Yogurt Plátano',      cat: 'Smoothies Yogurt', page: 'page9.html', cartName: 'Smoothie · Plátano' },
  { name: 'Smoothie Yogurt Zarzamora',    cat: 'Smoothies Yogurt', page: 'page9.html', cartName: 'Smoothie · Zarzamora' },
  { name: 'Smoothie Yogurt Maracuya',     cat: 'Smoothies Yogurt', page: 'page9.html', cartName: 'Smoothie · Maracuya' },
  { name: 'Latte Frío Clásico',           cat: 'Lattes Fríos',     page: 'page9.html', cartName: 'Latte Frío · Clásico' },
  { name: 'Latte Frío Vainilla',          cat: 'Lattes Fríos',     page: 'page9.html', cartName: 'Latte Frío · Vainilla' },
  { name: 'Latte Frío Moka',              cat: 'Lattes Fríos',     page: 'page9.html', cartName: 'Latte Frío · Moka' },
  { name: 'Latte Frío Crema de avellana', cat: 'Lattes Fríos',     page: 'page9.html', cartName: 'Latte Frío · Crema de avellana' },
  { name: 'Latte Frío Cajeta',            cat: 'Lattes Fríos',     page: 'page9.html', cartName: 'Latte Frío · Cajeta' },
  { name: 'Latte Frío Caramelo',          cat: 'Lattes Fríos',     page: 'page9.html', cartName: 'Latte Frío · Caramelo' },
  { name: 'Latte Frío Licor de café',     cat: 'Lattes Fríos',     page: 'page9.html', cartName: 'Latte Frío · Licor de café' },
  { name: 'Latte Frío Cacahuate',         cat: 'Lattes Fríos',     page: 'page9.html', cartName: 'Latte Frío · Cacahuate' },
  { name: 'Latte Frío Crema irlandesa',   cat: 'Lattes Fríos',     page: 'page9.html', cartName: 'Latte Frío · Crema irlandesa' },
  { name: 'Latte Frío Té chai',           cat: 'Lattes Fríos',     page: 'page9.html', cartName: 'Latte Frío · Té chai' },
  { name: 'Latte Frío Té matcha',         cat: 'Lattes Fríos',     page: 'page9.html', cartName: 'Latte Frío · Té matcha' },
  { name: 'Shaker Americano',             cat: 'Especiales',       page: 'page9.html', cartName: 'Especial · Shaker Americano' },
  { name: 'Shaker Capuccino',             cat: 'Especiales',       page: 'page9.html', cartName: 'Especial · Shaker Capuccino' },
  { name: 'Shaker Espresso',              cat: 'Especiales',       page: 'page9.html', cartName: 'Especial · Shaker Espresso' },
  { name: 'Bevanta Energizzante',         cat: 'Especiales',       page: 'page9.html', cartName: 'Bevanta Energizzante' },
  { name: 'Carajillo',                    cat: 'Especiales',       page: 'page9.html', cartName: 'Carajillo' },

  /* ── COMPLEMENTOS & EXTRAS ── */
  { name: 'Orden de papas a la francesa', cat: 'Complementos',     page: 'page10.html', cartName: 'Orden de papas a la francesa' },
  { name: 'Orden de Guacamole',           cat: 'Complementos',     page: 'page10.html', cartName: 'Orden de Guacamole' },
  { name: 'Pan brioche',                  cat: 'Complementos',     page: 'page10.html', cartName: 'Pan brioche' },
  { name: 'Croissant con mermelada',      cat: 'Complementos',     page: 'page10.html', cartName: 'Croissant' },

  /* ── PIZZAS ── */
  { name: 'Pizza Hawaiana',               cat: 'Pizzas',           page: 'page11.html', cartName: 'Hawaiana' },
  { name: 'Pizza Mexicana',               cat: 'Pizzas',           page: 'page11.html', cartName: 'Mexicana' },
  { name: 'Pizza Vegetariana',            cat: 'Pizzas',           page: 'page11.html', cartName: 'Vegetariana' },
  { name: 'Pizza Del mar',                cat: 'Pizzas',           page: 'page11.html', cartName: 'Del mar' },
  { name: 'Pizza Jamón serrano',          cat: 'Pizzas',           page: 'page11.html', cartName: 'Jamón serrano' },
  { name: 'Pizza Crema de avellanas',     cat: 'Pizzas',           page: 'page11.html', cartName: 'Crema de avellanas' },
];
